In [1]:
import pandas as pd
import os.path as Path
import numpy as np
import string as str

In [2]:
%load_ext autoreload
%autoreload 2
from data_bpm.interface.main import *
from data_bpm.ml_logic.preprocessor import *

In [3]:
data_for_ml = pd.read_csv('../raw_data/data_for_ml.csv',index_col=0)
data_for_ml

description  \
UserID                                                      
512.0   Experienced professional with the ability to c...   
652.0   I am a Product Owner at World Simplified UG, a...   
618.0   Designer & Problem Solver | CS Student | Aimin...   
96.0                                                  NaN   
194.0   As a product marketing manager at the JetBrain...   
...                                                   ...   
229.0   As a Senior Product Manager with over 12+ year...   
461.0   A lady with a previous marketing background an...   
10.0    A passionate Product Leader Focused on People,...   
249.0   Product Management, Data & Technology enthusia...   
677.0   Emerging Product Leader with 8+ years of exper...   

                                                 headline  \
UserID                                                      
512.0   General Manager - US Finance, Legal, HR, Accou...   
652.0               Tech product support intern at Holidu   
618.0                Making Interfaces Sexier - UI/UX/Dev   
96.0                                     Product & Growth   
194.0     Product marketing manager at JetBrains | Mentor   
...                                                   ...   
229.0                             Product Manager @ KAYAK   
461.0   Junior Product Designer✨| UX/UI | Figma | Rese...   
10.0    Product Leader & Mentor • Lead Product Manager...   
249.0                                 Product @HelloFresh   
677.0   Building New Ventures | Product @HelloFresh | ...   

                                location                   company  \
UserID                                                               
512.0   Carrollton, Texas, United States             orbis systems   
652.0            Berlin, Berlin, Germany                    holidu   
618.0            Berlin, Berlin, Germany  a.t.e.m. management gmbh   
96.0             Berlin, Berlin, Germany                     clink   
194.0            Berlin, Berlin, Germany                 jetbrains   
...                                  ...                       ...   
229.0            Berlin, Berlin, Germany                     kayak   
461.0            Berlin, Berlin, Germany                   velents   
10.0             Berlin, Berlin, Germany                   spryker   
249.0            Berlin, Berlin, Germany                hellofresh   
677.0        Dubai, United Arab Emirates                hellofresh   

                                                 jobTitle  \
UserID                                                      
512.0   General Manager, Orbis International Technolog...   
652.0                         Tech product support intern   
618.0                                        Web Designer   
96.0                             Chief Experience Officer   
194.0                           Product Marketing Manager   
...                                                   ...   
229.0                                     Product Manager   
461.0                             Junior Product Designer   
10.0                                 Lead Product Manager   
249.0                                 Director of Product   
677.0                         Product Lead, New Ventures    

                                           jobDescription  \
UserID                                                      
512.0   A highly driven professional leading the US op...   
652.0                                                 NaN   
618.0   Skills: Web Design · Cascading Style Sheets (C...   
96.0                                                  NaN   
194.0                                                 NaN   
...                                                   ...   
229.0                                                 NaN   
461.0   Velents AI is a hiring platform that will help...   
10.0    Skills: Product Management · Team Leadership ·...   
249.0   - Driving product alignment and prioritization...   
677.0   𝗞𝗲𝘆 𝗿𝗲𝘀𝗽𝗼𝗻𝘀𝗮𝗯

In [4]:
X_processed = preprocess_features(data_for_ml.drop(columns=['Attendance']), save_pipeline = True)


✅ MetadataTransformer constructor
✅ MetadataTransformer constructor
✅ MetadataTransformer is called for the first time
✅ X_processed, with shape (474, 34)
[[1.         0.07942238 0.48854962 ... 0.54997591 0.21428154 0.69186946]
 [1.         0.01805054 0.01908397 ... 0.1908353  0.43886729 0.33560341]
 [1.         0.06859206 0.12977099 ... 0.49946877 0.585145   0.29062143]
 ...
 [1.         0.07220217 0.02671756 ... 0.39042567 0.58771065 0.39970056]
 [1.         0.07581227 0.         ... 0.54954423 0.45180968 0.39370713]
 [1.         0.03249097 0.07251908 ... 0.32774429 0.08364515 0.49241546]]

Saving preprocessing pipeline to local disk...
✅ Preprocessing pipeline saved locally


In [5]:
y_train = data_for_ml['Attendance']

In [14]:
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, train_test_split
from sklearn.metrics import roc_auc_score
from scipy.stats import uniform, randint

# Assuming you have your data in X_train, X_test, y_train, y_test

# Define the XGBoost classifier
xgb_model = xgb.XGBClassifier(objective='binary:logistic', eval_metric='logloss')

# Define parameter grids for RandomizedSearchCV and GridSearchCV
param_grid_random = {
    'n_estimators': randint(290, 360),
    'learning_rate': uniform(0.3, 0.5),
    'max_depth': randint(3, 7),
    'min_child_weight': randint(1, 5),
    'subsample': uniform(0.5, 0.8),
    'colsample_bytree': uniform(0.6, 0.7),
    'gamma': uniform(0.3, 0.6),
}


# Perform RandomizedSearchCV
rand_search = RandomizedSearchCV(estimator=xgb_model, param_distributions=param_grid_random, n_iter=1000, scoring='roc_auc', cv=2, verbose=1, n_jobs=-1)
rand_search.fit(X_processed, y_train)
print("Best parameters found by RandomizedSearchCV:", rand_search.best_params_)
print("Best AUC score found by RandomizedSearchCV:", rand_search.best_score_)


Fitting 2 folds for each of 1000 candidates, totalling 2000 fits
Best parameters found by RandomizedSearchCV: {'colsample_bytree': 0.773041181465276, 'gamma': 0.4250180588095578, 'learning_rate': 0.7633999035607152, 'max_depth': 3, 'min_child_weight': 1, 'n_estimators': 311, 'subsample': 0.7897398402939455}
Best AUC score found by RandomizedSearchCV: 0.5738635633372475


/Users/yulka/.pyenv/versions/3.10.6/envs/data-bpm/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:547: FitFailedWarning: 
1286 fits failed out of a total of 2000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/yulka/.pyenv/versions/3.10.6/envs/data-bpm/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/yulka/.pyenv/versions/3.10.6/envs/data-bpm/lib/python3.10/site-packages/xgboost/core.py", line 730, in inner_f
    return func(**kwargs)
  File "/Users/yulka/.pyenv/versions/3.10.6/envs/data-bpm/lib/python3.10/site-packa

Fitting 5 folds for each of 1000 candidates, totalling 5000 fits
Best parameters found by RandomizedSearchCV: {'colsample_bytree': 0.7981976920904925, 'gamma': 0.1493851548677918, 'learning_rate': 0.2873836203172824, 'max_depth': 4, 'min_child_weight': 9, 'n_estimators': 202, 'subsample': 0.981672482605199}
Best AUC score found by RandomizedSearchCV: 0.5497622334713913



In [7]:

param_grid_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'min_child_weight': [1, 4, 9],
    'subsample': [0.6, 0.7, 0.8],
    'colsample_bytree': [0.6, 0.7, 0.8],
    'gamma': [0, 0.1, 0.2],
}
# Perform GridSearchCV
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid_grid, scoring='roc_auc', cv=5, verbose=1, n_jobs=-1)
grid_search.fit(X_processed, y_train)
print("Best parameters found by GridSearchCV:", grid_search.best_params_)
print("Best AUC score found by GridSearchCV:", grid_search.best_score_)

# Use the best model from GridSearchCV to predict probabilities
best_model = grid_search.best_estimator_
y_pred_proba = best_model.predict_proba(X_processed)[:, 1]




Fitting 5 folds for each of 2187 candidates, totalling 10935 fits
Best parameters found by GridSearchCV: {'colsample_bytree': 0.8, 'gamma': 0.2, 'learning_rate': 0.2, 'max_depth': 5, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.7}
Best AUC score found by GridSearchCV: 0.5470974952337124


NameError: name 'y_test' is not defined

In [8]:
# Calculate AUC score on the test set
auc_score = roc_auc_score(y_train, y_pred_proba)
print("AUC score on the test set:", auc_score)

AUC score on the test set: 1.0


In [14]:
!pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 6.4 MB/s eta 0:00:0000:0100:01
